# Generated by Django 5.0.6 on 2024-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text="id of user's tg chat", max_length=64, null=True,
                                   verbose_name='telegram chat id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="user's email", max_length=254, unique=True, verbose_name='почта'),
        ),
    ]
