# Generated by Django 5.0.6 on 2024-05-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='perform_at',
            field=models.TimeField(blank=True, help_text='время, когда необходимо выполнять привычку', null=True,
                                   verbose_name='Время'),
        ),
    ]
