# Generated by Django 5.0.6 on 2024-05-22 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_habit_next_perform_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='next_perform_at',
            field=models.DateTimeField(blank=True, help_text='время, в которое нужно выполнить привычку в следующий раз', null=True, verbose_name='Время следующего выполнения'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habit', to='habits.habit', verbose_name='Связанная привычка'),
        ),
    ]
